### ISSUE TITLE
wifi issue

### ISSUE THREAD

**Issue by siosos** [fsantini/KoboCloud#26] opened 2020-06-22 10:18 UTC
Hi 
I've installed kobocloud on my old Kobo Glo (with last firmware 4.21.15015). 
After install the kobo is not able to view any wifi networks (everything was ok before install).
After Uninstall KoboCloud the issue is still present. 

I have to reinstall firmware update to recover wifi. 
I tried several times with the last firmware and the March 2020 release (4.20.14622), but always have the same issue. 

Any idea ?
Thanks

**Comment by claudiosousa** [comment] 2020-06-27 20:11
Got the same issue with my Kobo Libra. Had to perform a manual reset to retrieve a wifi connection

**Comment by fsantini** [comment] 2020-06-28 07:53
Sorry, this is indeed unfortunate. It's quite strange because any action from the scripts should be initiated after wifi connection, so it shouldn't interfere with what happens before, but I'll try to investigate.

**Comment by alxsey** [comment] 2020-07-01 22:22
wifi problems look like ongoing Kobo issue. Not related to KoboCloud. I have several readers and most of them giving me really hard time with wifi. Should open bug with Kobo, I guess.

**Comment by juanitomaille** [comment] 2020-07-02 19:55
Same problem here. version 4.22.15190on Kobo Aura; no more wifi after installing !

**Comment by rambo-returns** [comment] 2020-07-14 02:24
Same here. How did you revert back?

**Comment by rambo-returns** [comment] 2020-07-14 02:26
> Hi
> I've installed kobocloud on my old Kobo Glo (with last firmware 4.21.15015).
> After install the kobo is not able to view any wifi networks (everything was ok before install).
> After Uninstall KoboCloud the issue is still present.
> 
> I have to reinstall firmware update to recover wifi.
> I tried several times with the last firmware and the March 2020 release (4.20.14622), but always have the same issue.
> 
> Any idea ?
> Thanks

How did you reinstall firmware update?

**Comment by juanitomaille** [comment] 2020-07-14 07:29
Ok, Iv'e managed to make working wifi again.
After installing kobocloud, i reverted back to old version of kobo firmware 4.19 maybe. After that it updated automatically and it work with kobocloud always installed.
That's it.

**Comment by asdalo21** [comment] 2020-08-04 17:17
Yep, same problem here. I am using a Clara HD with the 4.22 version of the firmware.

**Comment by mxbndr** [comment] 2020-12-06 06:37
Same issue with Libra H20 on November 2020 firmware. Wifi is basically permanently disabled and only fixed with a factory reset.

**Comment by mxbndr** [comment] 2020-12-06 06:47
Can confirm that Dropbox sync still works despite wifi issue. Google Drive does not. So, somehow the sync connection is hijacked by KoboCloud, and the Kobo is confused into thinking there is no wifi available. Attached are the log file and kobocloudrc file.
[get.log](https://github.com/fsantini/KoboCloud/files/5648386/get.log)

[kobocloudrc.zip](https://github.com/fsantini/KoboCloud/files/5648387/kobocloudrc.zip)

My guess is that the fact that Google Drive does not work is unrelated, and actually related to the file not being public (the Dropbox file can be accessed via an incognito browser, the Drive file cannot).

**Comment by mxbndr** [comment] 2020-12-06 07:03
I can repeat this issue every time. Interestingly, it also causes Windows to think something is wrong with the drive, though this doesn't appear to affect accessing it normally.

I can confirm the Google Drive issue is fixed with proper permissions on the links.

**Comment by mxbndr** [comment] 2020-12-06 07:32
If I use this file from the latest Assets links, I don't get a wifi issue, but I still get the Windows drive detection issue: https://github.com/fsantini/KoboCloud/releases/download/0.5/KoboRoot.tgz

It does not seem to matter, though.

Changing the kobocloudrc file at this stage also does not reproduce the wifi issue. However, syncing manually results in no books from either Dropbox or Google Drive. If I power off and then on again, both Google Drive and Dropbox files will show normally, presumably because the sync got the files and it was cached/queued somehow.

SO! This is the process I have found results in working wifi and mostly-working synced files:

1. Download https://github.com/fsantini/KoboCloud/releases/download/0.5/KoboRoot.tgz rather than compiling yourself. Add it to .kobo and reboot, as normal (I have to eject and disconnect to reboot the Libra H2O).
2. Change the kobocloudrc file at .add/kobocloud to have the right Dropbox or Google Drive etc links.
3. Sync the files manually on the Kobo device.
4. Power off (Sleep may be enough, not sure)
5. Power on, wait a minute for books to appear.

Latest log, for posterity:
[get.log](https://github.com/fsantini/KoboCloud/files/5648429/get.log)

**Comment by siosos** [comment] 2020-12-29 17:55
> If I use this file from the latest Assets links, I don't get a wifi issue, but I still get the Windows drive detection issue: https://github.com/fsantini/KoboCloud/releases/download/0.5/KoboRoot.tgz
> 
> It does not seem to matter, though.
> 
> Changing the kobocloudrc file at this stage also does not reproduce the wifi issue. However, syncing manually results in no books from either Dropbox or Google Drive. If I power off and then on again, both Google Drive and Dropbox files will show normally, presumably because the sync got the files and it was cached/queued somehow.
> 
> SO! This is the process I have found results in working wifi and mostly-working synced files:
> 
>     1. Download https://github.com/fsantini/KoboCloud/releases/download/0.5/KoboRoot.tgz rather than compiling yourself. Add it to .kobo and reboot, as normal (I have to eject and disconnect to reboot the Libra H2O).
> 
>     2. Reconnect the device, and change the kobocloudrc file at .add/kobocloud to have the right Dropbox or Google Drive etc links. Eject and disconnect.
> 
>     3. Sync the files manually on the Kobo device.
> 
>     4. Power off (Sleep may be enough, not sure)
> 
>     5. Power on, wait a minute for books to appear.
> 
> 
> Latest log, for posterity:
> [get (1).log](https://github.com/fsantini/KoboCloud/files/5710922/get.1.log)

Hello, 
This process works great on my Kobo Glo !
Thank you !

**Comment by siosos** [comment] 2020-12-29 17:57
works with process given by @mxbndr

**Closed** 2020-12-29 17:56 UTC
