### ISSUE TITLE
Kobo libra not sincronize file

### ISSUE THREAD

**Issue by Karmafly** [fsantini/KoboCloud#115] opened 2022-02-16 10:01 UTC
Hi dear, from one week i can't sincronyze no more file from Gdrive or Pcloud.

Can i send you the log?

**Comment by fsantini** [comment] 2022-02-16 10:07
Hi, yes please do. Either post it here, or send it to francesco.santini@gmail.com
Do you have the latest version installed?

**Comment by Karmafly** [comment] 2022-02-16 10:09
yes i have installed last version. i send you a file.

**Comment by fsantini** [comment] 2022-02-16 10:17
I investigated the problem and it's a duplicate of #112. I'm going to close this to follow up there.

**Closed by fsantini** 2022-02-16 10:17 UTC
